(() => {
  'use strict';const M=window.DemoModel,F=window.FlightModel,$=id=>document.getElementById(id),sim=new F.Flight(),history=new window.FlightCharts.Charts(sim);
  const fmt=(v,n=2)=>Number.isFinite(v)?v.toFixed(n):'—',clock=s=>{s=Math.round(s||0);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');};
  const labels={ready:'待起飞',running:'模拟飞行中',swapping:'中转站换电中',waiting:'原地等待中',paused:'已暂停',blocked:'保护停演',arrived:'已到达'};
  let selecting=null,selectingGust=false,lastPlan=-1,lastField=-1,lastStatus='',lastFrame=0,lastTelemetry=0;
  const bounds=L.latLngBounds(F.toLatLng({x:0,y:0}),F.toLatLng({x:60,y:40}));
  const wideBounds=L.latLngBounds([30.08,120.10],[30.31,120.47]);
  const overviewBounds=L.latLngBounds([30.105,120.15],[30.275,120.42]);
  const map=L.map('geoMap',{zoomControl:false,zoomSnap:.25,zoomDelta:.5,zoomAnimation:false,fadeAnimation:false,minZoom:10,maxZoom:17,maxBounds:wideBounds.pad(.08)}).fitBounds(overviewBounds,{padding:[20,20]});
  L.control.zoom({position:'bottomright'}).addTo(map);L.control.scale({imperial:false,position:'bottomleft'}).addTo(map);
  const notice=text=>{$('mapNotice').hidden=!text;$('mapNotice').textContent=text;};
  L.imageOverlay('vendor/xiaoshan-offline-map.svg',wideBounds,{pane:'tilePane',interactive:false,attribution:'底图数据 &copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> 贡献者 · ODbL · 内置快照 2026-09-23'}).addTo(map);
  let mapSource='offline',onlineTiles=null,tileLoads=0,tileErrors=0,mapSourceCycle=0;
  function setMapSource(source){
    const online=source==='online';mapSource=source;mapSourceCycle++;const cycle=mapSourceCycle;
    $('onlineMapBtn').setAttribute('aria-pressed',String(online));$('offlineMapBtn').setAttribute('aria-pressed',String(!online));
    $('onlineMapBtn').classList.toggle('selected',online);$('offlineMapBtn').classList.toggle('selected',!online);
    $('mapMeta').textContent=(online?'在线 OpenStreetMap':'内置地图快照')+' · 虚线框内为 12 × 8 km 飞行区';
    if(!online){if(onlineTiles&&map.hasLayer(onlineTiles))map.removeLayer(onlineTiles);map.setMaxBounds(wideBounds.pad(.08));if(!wideBounds.contains(map.getCenter()))map.fitBounds(overviewBounds,{padding:[20,20]});notice('');return;}
    map.setMaxBounds(null);tileLoads=0;tileErrors=0;notice('正在加载在线地图；连接不畅时仍显示内置底图。');
    if(!onlineTiles){onlineTiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors · <a href="https://www.openstreetmap.org/fixthemap" target="_blank" rel="noopener">反馈地图问题</a>'});
      onlineTiles.on('tileload',()=>{if(mapSource!=='online')return;tileLoads++;notice(tileErrors?'部分在线瓦片未加载，空白处由内置地图补齐。':'');});
      onlineTiles.on('tileerror',()=>{if(mapSource!=='online')return;tileErrors++;notice(tileLoads?'部分在线瓦片未加载，空白处由内置地图补齐。':'在线地图连接失败，当前仍显示内置地图。');});}
    onlineTiles.addTo(map);
    setTimeout(()=>{if(mapSourceCycle===cycle&&mapSource==='online'&&!tileLoads){setMapSource('offline');notice('在线地图在当前网络无法加载，已切换为内置地图。');}},12000);
  }
  const weather=new window.WeatherLayer(map,bounds,sim);
  L.rectangle(bounds,{color:'#a4e1da',weight:1.5,fill:false,dashArray:'6 6',interactive:false}).addTo(map);
  const baseline=L.polyline([],{color:'#263c56',weight:3,dashArray:'7 6',opacity:.7,interactive:false}).addTo(map),previous=L.polyline([],{color:'#d3a7db',weight:2,dashArray:'3 7',opacity:.75,interactive:false}).addTo(map),outline=L.polyline([],{color:'#0b302d',weight:7,opacity:.9,interactive:false}).addTo(map),pathLine=L.polyline([],{color:'#61ffde',weight:3,interactive:false}).addTo(map),trailLine=L.polyline([],{color:'#ffc354',weight:4,interactive:false}).addTo(map);
  const unsafeLine=L.polyline([],{color:'#ff4c72',weight:8,opacity:1,interactive:false}).addTo(map),comparisonLine=L.polyline([],{color:'#ac86ff',weight:4,dashArray:'9 6',opacity:1,interactive:false}).addTo(map);
  const lab=new window.MissionLab.Lab(sim,{unsafe:path=>unsafeLine.setLatLngs(path.map(F.toLatLng)),route:path=>comparisonLine.setLatLngs(path.map(F.toLatLng))});
  const pin=(letter,extra='')=>L.divIcon({html:`<span class="location-pin ${extra}">${letter}</span>`,className:'pin-container',iconSize:[30,30],iconAnchor:[15,15]});
  const point=(p,letter,title,extra='')=>L.marker(F.toLatLng(p),{icon:pin(letter,extra),title,draggable:extra!=='station-pin'}).addTo(map).bindTooltip(title,{permanent:true,direction:'bottom',offset:[0,16],className:'point-tooltip'});
  const startMarker=point(sim.start,'A','A · 起点'),endMarker=point(sim.end,'B','B · 终点','end-pin');
  const stationMarkers=F.STATIONS.map(s=>point(s,s.id,s.id+' · '+s.name,'station-pin'));let waypointMarkers=[];
  const drone=L.marker(F.toLatLng(sim.position),{icon:L.divIcon({html:'<span class="drone-icon"><img src="vendor/drone.svg" alt="无人机"></span>',className:'drone-container',iconSize:[44,44],iconAnchor:[22,22]}),interactive:false,keyboard:false,zIndexOffset:1000,title:'无人机模拟位置'}).addTo(map);
  const gustShapes=L.layerGroup().addTo(map);let probePoint=null;const probeMarker=L.circleMarker(F.toLatLng(sim.position),{radius:8,color:'#d1fff4',weight:2,fillColor:'#102333',fillOpacity:.7,interactive:false,className:'weather-probe-marker'}).bindTooltip('气象取样点',{permanent:true,direction:'top',className:'probe-tooltip'});
  function editPoint(which,latlng,index){try{const p=F.fromLatLng(latlng);which==='waypoint'?sim.setWaypoint(index,p):sim.setPoint(which,p);lastPlan=-1;selecting=null;clearPreset();$('pointHint').textContent='任务点已更新，航路、电量与时间已重新计算。';renderWaypoints();render();}catch(e){$('pointHint').textContent=e.message;renderPlan();renderWaypoints();}}
  startMarker.on('dragend',()=>editPoint('start',startMarker.getLatLng()));endMarker.on('dragend',()=>editPoint('end',endMarker.getLatLng()));
  function renderWaypoints(){waypointMarkers.forEach(m=>m.remove());waypointMarkers=sim.waypoints.map((p,i)=>point(p,'W'+(i+1),'W'+(i+1)+' · 途经点','waypoint-pin'));const locked=sim.elapsed>0||['running','swapping'].includes(sim.status);
    $('waypointList').innerHTML=sim.waypoints.length?sim.waypoints.map((p,i)=>`<li><span><b>W${i+1}</b> ${F.toLatLng(p).map(n=>n.toFixed(4)).join(', ')}</span><div><button data-waypoint="${i}" data-action="up" aria-label="上移途经点 W${i+1}" ${locked||i===0?'disabled':''}>↑</button><button data-waypoint="${i}" data-action="down" aria-label="下移途经点 W${i+1}" ${locked||i===sim.waypoints.length-1?'disabled':''}>↓</button><button data-waypoint="${i}" data-action="remove" aria-label="删除途经点 W${i+1}" ${locked?'disabled':''}>×</button></div></li>`).join(''):'<li class="empty-waypoint">未设置途经点，可直接规划至终点。</li>';
    $('addWaypoint').disabled=locked||sim.waypoints.length>=3;waypointMarkers.forEach((m,i)=>m.on('dragend',()=>editPoint('waypoint',m.getLatLng(),i)));
  }
  function drawProfile(){const c=$('profile'),r=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=r.width*dpr;c.height=r.height*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);const w=r.width,h=r.height,l=32,t=12,gw=w-l-15,gh=h-t-27,px=x=>l+x*gw,py=y=>t+(1-y/3)*gh;ctx.font='12px Consolas,monospace';ctx.fillStyle='#acbdd2';ctx.strokeStyle='#ffffff18';for(let v=0;v<=3;v++){ctx.beginPath();ctx.moveTo(l,py(v));ctx.lineTo(w-15,py(v));ctx.stroke();ctx.fillText(v,8,py(v)+4);}for(let i=0;i<=100;i+=25){ctx.textAlign='center';ctx.fillText(i+'%',px(i/100),h-4);}ctx.setLineDash([3,5]);ctx.strokeStyle='#e7c27466';ctx.beginPath();ctx.moveTo(l,py(1.8));ctx.lineTo(w-15,py(1.8));ctx.stroke();ctx.setLineDash([]);for(const[m,col,dash]of[[sim.baselineMetrics,'#b9c9dc',[5,4]],[sim.metrics,'#59e4cd',[]]]){if(!m?.length)continue;ctx.beginPath();m.profile.forEach((p,i)=>i?ctx.lineTo(px(p.distance/m.length),py(p.value)):ctx.moveTo(px(p.distance/m.length),py(p.value)));ctx.strokeStyle=col;ctx.lineWidth=2;ctx.setLineDash(dash);ctx.stroke();ctx.setLineDash([]);}}
  function renderPlan(){baseline.setLatLngs((sim.baseline||[]).map(F.toLatLng));previous.setLatLngs((sim.previousPath||[]).map(F.toLatLng));startMarker.setLatLng(F.toLatLng(sim.start));endMarker.setLatLng(F.toLatLng(sim.end));const used=new Set(sim.itinerary.filter(l=>l.swap).map(l=>l.target.id));stationMarkers.forEach((m,i)=>{m.setOpacity(sim.cfg.stationsEnabled?1:.3);m.getElement()?.classList.toggle('planned-station',used.has(F.STATIONS[i].id));});drawProfile();}
  function syncControls(){const c=sim.cfg;$('time').max=Math.max(60,Math.ceil(c.time));for(const[id,k]of[['payload','payload'],['capacity','capacity'],['charge','charge'],['risk','lambda'],['energyWeight','energyWeight'],['playback','playback'],['time','time'],['speed','speed'],['basePower','basePower'],['reserve','reserve'],['swapSeconds','swapSeconds']])$(id).value=c[k];$('dynamic').checked=c.dynamic;$('hardLimit').checked=c.hard;$('stationsEnabled').checked=c.stationsEnabled;document.querySelectorAll('[name=source]').forEach(e=>e.checked=c.sources.includes(e.value));$('chargeValue').textContent=c.charge+'%';$('riskValue').textContent=c.lambda;$('energyValue').textContent=c.energyWeight;$('timeValue').textContent='+'+c.time+' min';$('reserveValue').textContent=c.reserve+'%';$('speedValue').textContent=c.speed+' m/s';}
  function renderGustList(){const active=sim.activeGusts();$('gustLocation').textContent=`活动阵风 ${active.length} / ${F.MAX_GUSTS} · 风场叠加计算`;$('gustList').hidden=!active.length;$('gustList').innerHTML=active.map(g=>{const ll=F.toLatLng(g);return `<article><div><strong>${g.id} · ${g.name}</strong><small>${g.placement==='map'?'地图选点':'前方自动'} · ${ll[0].toFixed(5)}°N, ${ll[1].toFixed(5)}°E · 半径 ${g.radius} km</small><small>剩余 ${clock(g.endAt-sim.elapsed)} · 最后 60 秒衰减</small></div><button data-remove-gust="${g.id}" aria-label="移除 ${g.id} ${g.name}">移除</button></article>`;}).join('');$('manualGustLife').textContent=active.length?`当前有 ${active.length} 处阵风叠加；每处自注入起持续 240 个任务秒。全部消散最迟还需 ${clock(Math.max(...active.map(g=>g.endAt))-sim.elapsed)}。暂停与保护停演冻结时钟；安全原地等待继续计时并耗电。`:'当前没有活动的手动阵风。可逐处注入，最多同时 8 处；随机天气刷新不会清除阵风。';}
  function renderTelemetry(){renderProbe();lab.update();const c=sim.cfg,m=sim.remainingMetrics(),b=sim.baselineMetrics,s=sim.schedule(),percent=sim.remainingWh/c.capacity*100,ok=(sim.feasible||sim.status==='arrived')&&!(sim.swapRemaining>0&&sim.pending);
    $('flightStatus').textContent=labels[sim.status];$('flightStatus').dataset.state=sim.status;$('clockLabel').textContent=clock(sim.elapsed)+' / '+c.playback+'×';$('mapMeta').textContent=(mapSource==='online'?'在线 OpenStreetMap':'内置地图快照')+' · 虚线框内为 12 × 8 km 飞行区';$('weatherStamp').textContent=`模拟天气 · T + ${fmt(sim.data.time,1)} min · 非实测`;$('replanLabel').textContent=`规划 ${sim.replans} 次${sim.pending?' · 待节点更新':''}`;
    const ll=F.toLatLng(sim.position);$('positionLabel').textContent=`${ll[0].toFixed(5)}°N, ${ll[1].toFixed(5)}°E`;
    $('distanceMetric').innerHTML=`${ok?fmt(m.length):'—'} <small>km</small>`;$('distanceNote').textContent=`已飞 ${fmt(sim.travelKm)} km · 途经 ${sim.nextWaypoint}/${sim.waypoints.length}`;$('batteryMetric').innerHTML=`${fmt(percent,1)} <small>%</small>`;$('batteryNote').textContent=`当前 ${fmt(sim.remainingWh,1)} Wh · 累计耗能 ${fmt(sim.usedWh,1)} Wh`;$('energyMetric').innerHTML=`${ok?fmt(m.energyWh,1):'—'} <small>Wh</small>`;$('energyNote').textContent=`下一航段需 ${ok?fmt(s.nextLegEnergyWh,1):'—'} Wh`;$('exposureMetric').innerHTML=`${ok?fmt(m.mean):'—'} <small>m²/s²</small>`;$('exposureNote').textContent=`同途经顺序的最短基线 ${fmt(b?.mean)}`;
    $('batteryFill').style.width=Math.max(0,Math.min(100,percent))+'%';$('batteryFill').style.background=percent<c.reserve+10?'#ffb65c':'#59e4cd';$('reserveMark').style.left=c.reserve+'%';$('arrivalCharge').textContent=ok?`预计终点 ${fmt(s.arrivalWh/c.capacity*100,1)}% · 每块保留 ${c.reserve}%`:'无可行电量方案';
    $('timeHeadline').textContent=sim.status==='arrived'?'最终任务用时':'预计任务总用时';$('totalTime').textContent=ok?clock(s.etaSeconds):'—';$('timeEquation').textContent=ok?`飞行 ${clock(sim.flightSeconds+s.flightSeconds)} + 等待 ${clock(sim.holdSeconds)} + 换电 ${clock(sim.swapElapsed+s.swapSeconds)}`:(sim.status==='waiting'||sim.resumeStatus==='waiting'?'等待结束后重算总用时':'当前无可行航路');$('elapsedTime').textContent=clock(sim.elapsed);$('timeParts').textContent=`飞行 ${clock(sim.flightSeconds)} · 等待 ${clock(sim.holdSeconds)} · 换电 ${clock(sim.swapElapsed)}`;$('swapCount').textContent=ok?`${sim.completedSwaps} / ${sim.completedSwaps+s.futureSwaps} 次`:'—';$('stationPlan').textContent=!ok&&!sim.activeStation?'当前无可执行换电方案':sim.activeStation?`正在 ${sim.activeStation.id} 换电`:(s.stops.length?s.stops.join(' → ')+' · 每次 '+c.swapSeconds+' s':sim.status==='arrived'?'换电与飞行记录已完成':'当前剩余任务无需换电');
    $('swapProgress').hidden=sim.swapRemaining<=0;$('swapMessage').textContent=sim.activeStation?`${sim.activeStation.id} 换电：还需 ${Math.ceil(sim.swapRemaining)} 秒${sim.status==='paused'?'（暂停）':''}`:'';$('swapBar').max=c.swapSeconds;$('swapBar').value=c.swapSeconds-sim.swapRemaining;const holding=sim.status==='waiting'||(sim.status==='paused'&&sim.resumeStatus==='waiting');$('holdProgress').hidden=!holding;$('holdMessage').textContent=holding?`安全位置等待：距阵风结束约 ${Math.max(0,Math.ceil((sim.waitUntil||sim.elapsed)-sim.elapsed))} 秒 · 已等待 ${clock(sim.holdSeconds)} · 已耗电 ${fmt(sim.holdEnergyWh,1)} Wh（等待累计）${sim.status==='paused'?' · 暂停':''}`:'';$('holdBar').max=240;$('holdBar').value=holding?240-Math.max(0,(sim.waitUntil||sim.elapsed)-sim.elapsed):0;
    $('insight').textContent=sim.status==='arrived'?`任务完成：总用时 ${clock(sim.elapsed)} = 飞行 ${clock(sim.flightSeconds)} + 等待 ${clock(sim.holdSeconds)} + ${sim.completedSwaps} 次换电 × ${c.swapSeconds} 秒。已按顺序访问 ${sim.nextWaypoint} 个途经点。`:sim.reason||(sim.swapRemaining>0?'无人机停留在换电站。固定等待结束后恢复满电，重新规划下一段航路。':sim.pending?'将在下一网格节点更新剩余任务与换电链。':`${sim.planMode}方案通过逐航段电量校验。总用时包含飞行与固定换电，暂停不计时。`);$('insight').classList.toggle('alert',!sim.feasible||sim.status==='blocked');
    $('playBtn').textContent=['running','swapping','waiting'].includes(sim.status)?'Ⅱ 暂停':sim.status==='arrived'?'✓ 已到达':sim.elapsed>0?'▶ 继续任务':'▶ 开始任务';$('playBtn').disabled=sim.status==='arrived'||(!sim.feasible&&sim.edgeProgress===0&&!(sim.status==='paused'&&sim.resumeStatus==='waiting')&&sim.status!=='waiting');$('gustBtn').disabled=!sim.canInjectGust();$('mapGustBtn').disabled=$('gustBtn').disabled;
    const locked=sim.elapsed>0||['running','swapping'].includes(sim.status);for(const id of ['payload','capacity','charge','reserve','basePower','swapSeconds','stationsEnabled','setStart','setEnd'])$(id).disabled=locked;$('speed').disabled=sim.status==='arrived';$('addWaypoint').disabled=locked||sim.waypoints.length>=3;document.querySelectorAll('[data-waypoint]').forEach(e=>{const i=Number(e.dataset.waypoint);e.disabled=locked||(e.dataset.action==='up'&&i===0)||(e.dataset.action==='down'&&i===sim.waypoints.length-1);});
    $('eventLog').innerHTML=sim.logs.slice(0,6).map(l=>`<li><time>${clock(l.at)}</time><span>${l.text}</span></li>`).join('');
    $('exampleWaypoints').disabled=locked;$('previewWeather').disabled=locked;$('refreshWeather').disabled=sim.status==='arrived';
    document.querySelectorAll('[data-preset]').forEach(e=>{const active=(Number(e.dataset.preset)!==0)===sim.cfg.stationsEnabled;e.classList.toggle('active',active);e.setAttribute('aria-pressed',String(active));});
    renderGustList();$('mapGustBtn').classList.toggle('selected',selectingGust);$('mapGustBtn').setAttribute('aria-pressed',String(selectingGust));$('gustSelectHint').hidden=!selectingGust;
    $('mapSetStart').disabled=locked;$('mapSetEnd').disabled=locked;$('mapAddWaypoint').disabled=locked||sim.waypoints.length>=3;
    [startMarker,endMarker,...waypointMarkers].forEach(m=>locked?m.dragging.disable():m.dragging.enable());
    $('mapEditHint').textContent=locked?'任务进行中；点击“重置并编辑”调整 A / B / W':selecting?'点击地图边框内设置'+({start:'起点 A',end:'终点 B',waypoint:'途经点'}[selecting]):'拖动 A / B / W，或点击按钮后在图内选点';
    map.getContainer().classList.toggle('selecting-point',!!selecting||selectingGust);for(const [id,key]of[['mapSetStart','start'],['mapSetEnd','end'],['mapAddWaypoint','waypoint'],['setStart','start'],['setEnd','end'],['addWaypoint','waypoint']])$(id).classList.toggle('selected',selecting===key);
    const live=sim.instantaneous();$('mapSpeed').textContent=`空速 ${fmt(c.speed,1)} · 地速 ${fmt(sim.status==='running'?live.groundSpeed:0,1)} m/s`;renderSpeedCurve();$('powerTitle').textContent=live.holding?'当前悬停功率':live.preview?'下一航段功率':'当前航段功率';$('powerMetric').textContent=fmt(live.powerW/1000,2)+' kW';$('powerNote').textContent=live.holding?`${fmt(live.powerW/60,1)} Wh/min · 原地等待继续耗电`:live.powerW?`${fmt(live.powerW/60,1)} Wh/min · 较同空速无风 +${fmt((live.powerW/live.calmPower-1)*100,0)}%`:'暂停 / 地面换电 / 停演期间不累计飞行能耗';
    $('groundSpeedMetric').textContent=`${fmt(live.groundSpeed,1)} / ${c.speed} m/s`;$('groundSpeedNote').textContent=`当前航段风速 ${fmt(live.windSpeed,1)} m/s · 空速与地速不同`;$('energyRateMetric').textContent=live.holding?'—':sim.path?fmt(live.whPerKm,1)+' Wh/km':'—';$('energyRateNote').textContent=live.holding?'原地等待距离为零；按 Wh/min 计算耗电':sim.data.field.events.length?(live.localGust>.03?'已受阵风影响：功率与地速共同决定耗电':'当前位置在阵风区外；前方阵风不会令此处耗电突增'):'耗电 = 功率 × 时间；逆风降低地速，增加每公里耗电';
    const decision=sim.decision;$('gustAction').textContent=(sim.gusts.length&&!(sim.data.field.events||[]).length?'手动阵风已消散 · 当前天气继续演化':decision?.action)||'未注入阵风 · 按当前风场规划';$('gustDetail').textContent=decision?.detail||'注入后会标出影响范围，立即从当前位置检查绕行、换电和保留电量。强风核心独立于风险权重，始终禁入。';$('gustDecision').classList.toggle('danger',!!decision&&!sim.feasible);
    $('gustComparison').textContent=decision?`旧航线受影响峰值：${fmt(decision.peakWind,1)} m/s / ${fmt(decision.peakPower/1000,2)} kW（假设继续原路线）${decision.after&&sim.feasible&&decision.baselineAvailable!==false?`；新计划较触发前：航段能耗 ${decision.after.energyWh-decision.before.energyWh>=0?'+':''}${fmt(decision.after.energyWh-decision.before.energyWh,1)} Wh，飞行时间 ${decision.after.timeMinutes-decision.before.timeMinutes>=0?'+':''}${fmt(decision.after.timeMinutes-decision.before.timeMinutes,1)} min`:''}`:'风速 ≥ 14 m/s、地速 < 3 m/s 或进入强风核心时，该航段不可执行；均为教学阈值。';const assessment=sim.waitAssessment();$('waitGust').disabled=!assessment.allowed;$('waitAdvice').hidden=!(['blocked','waiting'].includes(sim.status)||sim.resumeStatus==='waiting');$('waitAdvice').textContent=sim.status==='waiting'||sim.resumeStatus==='waiting'?`已选择原地等待；地速为零，预计在任务时间 ${clock(sim.waitUntil||sim.elapsed)} 结束后自动重规划。可暂停或清除阵风。`:sim.status==='blocked'?`等待方案：${assessment.reason}${assessment.allowed?' 点击“安全位置原地等待”继续演示。':' 请清除阵风或重置调整任务；实际飞行须按机型应急程序处置。'}`:'';$('clearGust').disabled=!sim.activeGusts().length;
  }
  function renderSpeedCurve(){const a=sim.path?.[sim.index],b=sim.path?.[sim.index+1];const speeds=[6,9,12,15,18,sim.cfg.speed];const values=[...new Set(speeds)].sort((x,y)=>x-y);$('speedCurve').innerHTML=values.map(v=>{const e=a&&b?window.WeatherPhysics.edge(a,b,{...sim.cfg,speed:v}):null;return `<article class="speed-option ${v===sim.cfg.speed?'active':''}"><b>${v} m/s</b><span>${e?.flyable?fmt(e.powerW/1000,2)+' kW':'—'}</span><strong>${e?.flyable?fmt(e.whPerKm,1)+' Wh/km':'不可飞'}</strong></article>`;}).join('');}
  function renderProbe(){
    const p=probePoint||sim.position,d=sim.weatherAt(p),ll=F.toLatLng(p);$('probeFollow').setAttribute('aria-pressed',String(!probePoint));$('probeLocation').textContent=(probePoint?'取样点':'无人机位置')+' · '+ll.map(n=>n.toFixed(4)).join(', ')+' · T+'+fmt(sim.data.time,2)+' min';
    if(probePoint){probeMarker.setLatLng(ll);if(!map.hasLayer(probeMarker))probeMarker.addTo(map);}else if(map.hasLayer(probeMarker))probeMarker.remove();
    for(const [id,value]of[['probeMean',d.mean_horizontal_speed],['probeWind',d.horizontal_speed],['probeSigma',d.sigma],['probeTke',d.tke]])$(id).textContent=fmt(value,3);
    $('probeEquation').textContent=d.available?'模型关系：K = ½(σu² + σv² + σw²) = 1.5σ²；本点由方差回算 K ≈ '+fmt(d.tke_from_variances,3)+' m²/s²。':'没有观测数据，风与湍流读数不可用。';
    $('probeVector').textContent=d.available?'此刻脉动 u′ / v′ / w′ = '+[d.fluctuation.u,d.fluctuation.v,d.fluctuation.w].map(v=>fmt(v,2)).join(' / ')+' m/s；背景与脉动按方向合成，不能直接相加风速大小。':'';
  }
  function renderWeatherLife(){const stamp=t=>{const seconds=Math.round(Math.abs(t)*60);return 'T'+(t<0?'−':'+')+String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');};const events=sim.data.events||[],active=events.filter(e=>e.strength>0),rows=[...active,...events.filter(e=>e.phase==='尚未生成').slice(0,1),...events.filter(e=>e.phase==='已消散').slice(-1)].slice(0,5);$('weatherSeed').textContent='种子 '+sim.cfg.seed;$('weatherLifeCount').textContent=active.length+' 个活跃斑块 · '+stamp(sim.data.time);$('weatherEvents').innerHTML=rows.map(e=>'<article><b>'+e.id+' · '+e.phase+'</b><span>开始 '+stamp(e.start)+' → 结束 '+stamp(e.end)+'</span><progress max="1" value="'+e.progress+'"></progress></article>').join('');}
  function drawWeather(){weather.draw();renderWeatherLife();gustShapes.clearLayers();for(const g of sim.data.field.events||[]){L.circle(F.toLatLng(g),{radius:g.radius*1000,color:'#ffb84e',weight:2,dashArray:'7 5',fillColor:'#ffb84e',fillOpacity:.1,interactive:false,className:'gust-envelope'}).addTo(gustShapes);L.circleMarker(F.toLatLng(g),{radius:6,color:'#fff2d5',weight:2,fillColor:'#ff8135',fillOpacity:1,interactive:false,className:'gust-center'}).addTo(gustShapes).bindTooltip(g.id+' · '+g.name+' · 影响半径 '+g.radius+' km',{permanent:true,direction:'top',className:'gust-tooltip'});if(g.core)L.circle(F.toLatLng(g),{radius:(g.radius*g.core+window.WeatherPhysics.BUFFER)*1000,color:'#ff626d',weight:2,fillColor:'#ef4054',fillOpacity:.23,interactive:false,className:'gust-core'}).addTo(gustShapes);}}
  function renderMoving(){drone.setLatLng(F.toLatLng(sim.position));const rest=sim.remainingPath().map(F.toLatLng);pathLine.setLatLngs(rest);outline.setLatLngs(rest);trailLine.setLatLngs([...sim.trail,sim.position].map(F.toLatLng));drone.getElement()?.classList.toggle('swapping-drone',sim.swapRemaining>0);}
  function render(){if(lastPlan!==sim.replans){lastPlan=sim.replans;renderPlan();}if(lastField!==sim.fieldRevision){lastField=sim.fieldRevision;drawWeather();}renderMoving();renderTelemetry();history.update(true);lastStatus=sim.status;}
  const clearPreset=()=>document.querySelectorAll('[data-preset]').forEach(e=>{e.classList.remove('active');e.setAttribute('aria-pressed','false');});
  function change(patch){try{sim.configure(patch);clearPreset();syncControls();render();}catch(e){$('insight').textContent=e.message;syncControls();}}
  for(const[id,key]of[['payload','payload'],['capacity','capacity'],['charge','charge'],['risk','lambda'],['energyWeight','energyWeight'],['time','time'],['speed','speed'],['basePower','basePower'],['reserve','reserve'],['swapSeconds','swapSeconds']])$(id).addEventListener(id==='speed'?'change':$(id).type==='range'?'input':'change',e=>{if(!e.target.checkValidity()||e.target.value===''){syncControls();$('insight').textContent='请输入控件允许范围内的数值。';return;}change({[key]:Number(e.target.value)});});
  $('speed').addEventListener('input',e=>{$('speedValue').textContent=e.target.value+' m/s';});
  $('playback').addEventListener('change',e=>{sim.cfg.playback=Number(e.target.value);renderTelemetry();});$('dynamic').addEventListener('change',e=>change({dynamic:e.target.checked}));$('hardLimit').addEventListener('change',e=>change({hard:e.target.checked}));$('stationsEnabled').addEventListener('change',e=>change({stationsEnabled:e.target.checked}));document.querySelectorAll('[name=source]').forEach(e=>e.addEventListener('change',()=>change({sources:[...document.querySelectorAll('[name=source]:checked')].map(e=>e.value)})));
  function layer(mode){weather.setMode(mode);document.querySelectorAll('[data-layer]').forEach(e=>{e.classList.toggle('selected',e.dataset.layer===mode);e.setAttribute('aria-pressed',String(e.dataset.layer===mode));});$('weatherLegend').innerHTML=mode==='wind'?'瞬时水平风速 0 <i class="wind-gradient"></i> 24 m/s · 粒子表示水平风向':mode==='fluctuation'?'单方向波动 σ：0 <i class="fluct-gradient"></i> 1.414 m/s · 紫色系 · σ = √(2K/3)':mode==='none'?'气象叠加已关闭':`TKE 0 <i class="tke-gradient"></i> 3 m²/s² · 绿黄红色系${mode==='combined'?' · 叠加白色风粒子':''}`;}
  document.querySelectorAll('[data-layer]').forEach(e=>e.addEventListener('click',()=>layer(e.dataset.layer)));$('layerOpacity').addEventListener('input',e=>weather.setOpacity(Number(e.target.value)/100));
  $('gustList').addEventListener('click',e=>{const button=e.target.closest('[data-remove-gust]');if(button){sim.removeGust(button.dataset.removeGust);render();}});
  $('playBtn').addEventListener('click',()=>{selecting=null;selectingGust=false;['running','swapping','waiting'].includes(sim.status)?sim.pause():sim.run();render();});$('gustBtn').addEventListener('click',()=>{selectingGust=false;sim.gust($('gustType').value);render();});$('mapGustBtn').addEventListener('click',()=>{selectingGust=!selectingGust;selecting=null;if(selectingGust){$('pointHint').textContent='任务点选择已取消；阵风中心请在地图内点击。';$('gustSelectHint').textContent='点击地图边框内选取阵风中心；再次点击按钮或按 Esc 取消。';}else $('pointHint').textContent='点击按钮，再在地图边框内选点。';renderTelemetry();});$('clearGust').addEventListener('click',()=>{selectingGust=false;sim.clearGust();render();});$('waitGust').addEventListener('click',()=>{sim.waitOutGust();render();});$('fitBtn').addEventListener('click',()=>map.fitBounds(bounds,{padding:[35,55]}));$('wideMapBtn').addEventListener('click',()=>map.fitBounds(wideBounds,{padding:[20,20]}));
  $('onlineMapBtn').addEventListener('click',()=>setMapSource('online'));
  $('offlineMapBtn').addEventListener('click',()=>setMapSource('offline'));
  setMapSource('online');
  function reset(){sim.reset();lastPlan=-1;lastField=-1;selecting=null;selectingGust=false;$('pointHint').textContent='点击按钮，再在地图边框内选点。';syncControls();renderWaypoints();render();}
  $('resetBtn').addEventListener('click',reset);document.querySelectorAll('[data-preset]').forEach(e=>e.addEventListener('click',()=>{sim.cfg.time=sim.clock;sim.cfg.stationsEnabled=Number(e.dataset.preset)!==0;reset();}));
  $('exampleWaypoints').addEventListener('click',()=>{try{sim.assertEditable();sim.waypoints=[{x:21,y:30},{x:43,y:12}].filter(p=>![sim.start,sim.end].some(q=>q.x===p.x&&q.y===p.y));reset();}catch(e){$('pointHint').textContent=e.message;}});
  $('refreshWeather').addEventListener('click',()=>{let seed=crypto.getRandomValues(new Uint32Array(1))[0];if(seed===sim.cfg.seed)seed=(seed+1)>>>0;sim.refreshWeather(seed);render();});
  $('previewWeather').addEventListener('click',()=>{sim.previewWeather(2);syncControls();render();});
  $('mapResetEdit').addEventListener('click',reset);
  for(const[btn,which]of[['setStart','start'],['setEnd','end'],['addWaypoint','waypoint'],['mapSetStart','start'],['mapSetEnd','end'],['mapAddWaypoint','waypoint']])$(btn).addEventListener('click',()=>{selectingGust=false;selecting=which;$('pointHint').textContent=`请在边框内点击设置${which==='start'?'起点 A':which==='end'?'终点 B':'下一个途经点'}，吸附至 200 m 网格。`;renderTelemetry();});
  $('waypointList').addEventListener('click',e=>{const b=e.target.closest('[data-waypoint]');if(!b)return;try{const i=Number(b.dataset.waypoint);b.dataset.action==='remove'?sim.removeWaypoint(i):sim.moveWaypoint(i,b.dataset.action==='up'?-1:1);lastPlan=-1;renderWaypoints();render();}catch(err){$('pointHint').textContent=err.message;}});
  $('probeFollow').addEventListener('click',()=>{probePoint=null;renderProbe();});
  map.on('click',e=>{if(selectingGust){if(!bounds.contains(e.latlng)){$('gustSelectHint').textContent='请在虚线边框内点击，阵风中心必须位于教学区域。';return;}try{const p=F.fromLatLngExact(e.latlng);if(!sim.gust($('gustType').value,p))throw Error('当前没有可用的剩余航路，请先清除阵风或重置任务。');selectingGust=false;$('pointHint').textContent='点击按钮，再在地图边框内选点。';render();}catch(error){selectingGust=false;$('gustDetail').textContent=error.message;renderTelemetry();}return;}if(!selecting){if(bounds.contains(e.latlng)){const ref=F.toLatLng({x:0,y:0}),unit=F.toLatLng({x:1,y:1});probePoint={x:Math.max(0,Math.min(60,(e.latlng.lng-ref[1])/(unit[1]-ref[1]))),y:Math.max(0,Math.min(40,(e.latlng.lat-ref[0])/(unit[0]-ref[0])))};renderProbe();}return;}try{selecting==='waypoint'?sim.addWaypoint(F.fromLatLng(e.latlng)):sim.setPoint(selecting,F.fromLatLng(e.latlng));selecting=null;lastPlan=-1;lastField=-1;clearPreset();$('pointHint').textContent='任务点已更新，可继续设置或开始任务。';renderWaypoints();render();}catch(error){$('pointHint').textContent=error.message;}});
  function loop(now){const dt=lastFrame?Math.min((now-lastFrame)/1000,.15):0;lastFrame=now;if(['running','swapping','waiting'].includes(sim.status)){sim.tick(dt*sim.cfg.playback);if(lastPlan!==sim.replans){lastPlan=sim.replans;renderPlan();}if(lastField!==sim.fieldRevision){lastField=sim.fieldRevision;drawWeather();}renderMoving();if(now-lastTelemetry>200||lastStatus!==sim.status){renderTelemetry();history.update();lastTelemetry=now;lastStatus=sim.status;}}weather.animate(dt);requestAnimationFrame(loop);}requestAnimationFrame(loop);
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&selectingGust){selectingGust=false;$('pointHint').textContent='点击按钮，再在地图边框内选点。';renderTelemetry();}});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&['running','swapping','waiting'].includes(sim.status)){sim.pause();renderTelemetry();}});
  function openDialog(key){const item=window.DemoContent[key];$('dialogTitle').textContent=item.title;$('dialogBody').innerHTML=item.html;$('infoDialog').showModal();}
  for(const[id,key]of[['methodBtn','method'],['sourceBtn','sources'],['dataBtn','data'],['guideBtn','guide']])$(id).addEventListener('click',()=>openDialog(key));$('closeDialog').addEventListener('click',()=>$('infoDialog').close());
  $('exportBtn').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({...sim.snapshot(),display_layer:weather.mode,weather_probe:{...sim.weatherAt(probePoint||sim.position),follows_drone:!probePoint,coordinate:F.toLatLng(probePoint||sim.position)}},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='萧山低空换电任务记录.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  window.addEventListener('resize',()=>{map.invalidateSize();drawProfile();});syncControls();renderWaypoints();render();
  if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'read_flight_experiment',title:'读取换电飞行实验',description:'读取模拟航路、途经顺序、换电记录、电量与总用时。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>sim.snapshot()},{signal:lifecycle.signal})).catch(()=>{});}catch{}}
})();
