const assert=require('node:assert/strict');const M=require('../model.js');const F=require('../flight-engine.js');
const near=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
const active=s=>['running','swapping'].includes(s.status);
function complete(s,dt=.7){s.run();let steps=0;while(active(s)&&steps++<10000)s.tick(dt);assert.equal(s.status,'arrived');near(s.elapsed,s.flightSeconds+s.swapElapsed);near(s.swapElapsed,s.completedSwaps*s.cfg.swapSeconds);assert.ok(s.remainingWh>=s.reserveWh-1e-6);return s;}
let comparisons=0;for(const time of [0,40])for(const lambda of [0,8,20])for(const hard of [false,true]){const f=M.buildField({time}).field,a=M.plan(f,lambda,hard),d=M.plan(f,lambda,hard,false);assert.equal(!!a.path,!!d.path);if(a.path)near(M.metrics(a.path,lambda).cost,M.metrics(d.path,lambda).cost);comparisons++;}
near(M.metrics(M.plan(new Float64Array(2501).fill(.3),0).path,0).length,10.4);
const noSwap=new F.Flight();noSwap.configure({dynamic:false,stationsEnabled:false});assert.ok(!noSwap.feasible);
const defaultMission=new F.Flight();defaultMission.configure({dynamic:false});assert.ok(defaultMission.feasible);assert.ok(defaultMission.schedule().futureSwaps>=1);const prediction=defaultMission.schedule(),initialBattery=defaultMission.remainingWh;complete(defaultMission);near(defaultMission.elapsed,prediction.totalSeconds);near(defaultMission.usedWh,prediction.energyWh);near(defaultMission.remainingWh,prediction.arrivalWh);assert.ok(defaultMission.usedWh>initialBattery-defaultMission.reserveWh);
const pauseSwap=new F.Flight();pauseSwap.configure({dynamic:false});pauseSwap.run();let n=0;while(pauseSwap.status==='running'&&n++<1000)pauseSwap.tick(1);assert.equal(pauseSwap.status,'swapping');const position={...pauseSwap.position},beforeWh=pauseSwap.remainingWh;pauseSwap.tick(20);assert.deepEqual(pauseSwap.position,position);near(pauseSwap.remainingWh,beforeWh);near(pauseSwap.swapRemaining,100-(pauseSwap.elapsed-pauseSwap.flightSeconds-20));
pauseSwap.pause();const elapsed=pauseSwap.elapsed,remaining=pauseSwap.swapRemaining;pauseSwap.tick(100);near(pauseSwap.elapsed,elapsed);near(pauseSwap.swapRemaining,remaining);pauseSwap.run();assert.equal(pauseSwap.status,'swapping');pauseSwap.tick(remaining);near(pauseSwap.remainingWh,pauseSwap.cfg.capacity);assert.equal(pauseSwap.completedSwaps,1);
const waypoints=new F.Flight();waypoints.configure({dynamic:false});waypoints.addWaypoint({x:21,y:30});waypoints.addWaypoint({x:43,y:12});const wpPrediction=waypoints.schedule();assert.ok(waypoints.feasible);complete(waypoints);assert.equal(waypoints.nextWaypoint,2);assert.deepEqual(waypoints.visits.map(x=>x.index),[0,1]);near(waypoints.elapsed,wpPrediction.totalSeconds);
const short=new F.Flight();short.configure({dynamic:false});short.setPoint('end',{x:10,y:20});assert.equal(short.schedule().futureSwaps,0);complete(short);assert.equal(short.completedSwaps,0);
const endpointStation=new F.Flight();endpointStation.configure({dynamic:false});endpointStation.setPoint('end',{x:17,y:18});assert.equal(endpointStation.schedule().futureSwaps,0);complete(endpointStation);assert.equal(endpointStation.completedSwaps,0);
const startStation=new F.Flight();startStation.configure({dynamic:false,capacity:100,charge:25});startStation.setPoint('start',{x:17,y:18});startStation.setPoint('end',{x:25,y:18});assert.ok(startStation.feasible);assert.ok(startStation.itinerary[0].swap);complete(startStation);assert.equal(startStation.completedSwaps,1);
const noData=new F.Flight();noData.configure({sources:[]});assert.ok(!noData.feasible);assert.equal(noData.path,null);
const partial=new F.Flight();partial.configure({dynamic:false});const expectedArrival=partial.schedule().arrivalWh;partial.run();partial.tick(7.3);near(partial.schedule().arrivalWh,expectedArrival);complete(partial);near(partial.remainingWh,expectedArrival);
const barrier=new Float64Array(2501).fill(.3);for(let y=0;y<M.NY;y++)barrier[y*M.NX+30]=2;assert.equal(M.plan(barrier,8,true).path,null);
const ll=F.toLatLng({x:35,y:27});assert.deepEqual(F.fromLatLng({lat:ll[0],lng:ll[1]}),{x:35,y:27});assert.throws(()=>noData.setPoint('end',{x:61,y:20}));
const dynamic=new F.Flight();dynamic.run();for(let i=0;i<60;i++){const p={...dynamic.position};dynamic.tick(.5);assert.ok(Math.hypot(p.x-dynamic.position.x,p.y-dynamic.position.y)<=.5*(dynamic.cfg.speed+14)/F.CELL+1e-6);}const count=dynamic.replans;dynamic.gust();for(let i=0;i<80;i++)dynamic.tick(.5);assert.ok(dynamic.replans>count);assert.throws(()=>dynamic.addWaypoint({x:30,y:20}));
for(const points of [[],[{x:21,y:30},{x:43,y:12}]]){const live=new F.Flight();for(const p of points)live.addWaypoint(p);complete(live,1);assert.equal(live.nextWaypoint,points.length);assert.ok(live.replans>10);}
console.log(`PASS: ${comparisons} A*/Dijkstra comparisons; direct infeasibility vs swap reachability; complete mission ETA and energy; fixed swap and pause; ordered waypoints; no unnecessary swap; station start/end; partial-edge energy; no data; hard barrier; coordinates; continuous replanning; complete dynamic missions.`);
