const assert=require('node:assert/strict'),M=require('../model.js'),F=require('../flight-engine.js'),W=require('../weather-physics.js');
const near=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
function complete(s){let n=0;while(['running','swapping'].includes(s.status)&&n++<6000)s.tick(.7);assert.equal(s.status,'arrived');near(s.elapsed,s.flightSeconds+s.swapElapsed);assert.ok(s.remainingWh>=s.reserveWh-1e-6);}
const cfg={...F.DEFAULTS},a={x:0,y:0,value:.3,u:0,v:0},b={...a,x:1};
const calm=W.edge(a,b,cfg),head=W.edge({...a,u:-6},{...b,u:-6},cfg),tail=W.edge({...a,u:6},{...b,u:6},cfg),cross=W.edge({...a,v:8},{...b,v:8},cfg);
assert.ok(head.groundSpeed<calm.groundSpeed);assert.ok(head.powerW>calm.powerW);assert.ok(head.whPerKm>calm.whPerKm*2);assert.ok(tail.groundSpeed>calm.groundSpeed);assert.ok(cross.groundSpeed<calm.groundSpeed);assert.ok(!W.edge({...a,u:-13},{...b,u:-13},cfg).flyable);
const f=new F.Flight();f.configure({dynamic:false});f.run();f.tick(5);const p={...f.position},elapsed=f.elapsed,energy=f.usedWh,old=f.remainingPath().map(p=>[p.x,p.y]);f.gust('strong');assert.deepEqual(f.position,p);near(f.elapsed,elapsed);near(f.usedWh,energy);assert.ok(f.feasible);assert.ok(f.decision.unsafe>0);assert.notDeepEqual(f.remainingPath().map(p=>[p.x,p.y]),old);
for(let i=1;i<f.remainingPath().length;i++)assert.ok(W.safeSegment(f.data.field,f.remainingPath()[i-1],f.remainingPath()[i],f.cfg));f.gusts[0].endAt=Infinity;f.replan('固定风况积分测试');const predicted=f.schedule();complete(f);near(f.elapsed,predicted.etaSeconds);near(f.remainingWh,predicted.arrivalWh);
const zero=new F.Flight();zero.configure({dynamic:false,lambda:0,energyWeight:0,capacity:600});zero.gust('strong');assert.ok(zero.feasible);for(let i=1;i<zero.fullPath.length;i++)assert.ok(W.safeSegment(zero.data.field,zero.fullPath[i-1],zero.fullPath[i],zero.cfg));
const blocked=new F.Flight();blocked.configure({dynamic:false});blocked.run();blocked.tick(5);const pos={...blocked.position},time=blocked.elapsed,wh=blocked.remainingWh;blocked.gust('wide');assert.equal(blocked.status,'blocked');assert.ok(!blocked.feasible);blocked.tick(100);assert.deepEqual(blocked.position,pos);near(blocked.elapsed,time);near(blocked.remainingWh,wh);assert.equal(blocked.instantaneous().powerW,0);blocked.clearGust();assert.ok(blocked.feasible);assert.equal(blocked.status,'paused');blocked.run();assert.equal(blocked.status,'running');
const moderate=new F.Flight();moderate.configure({dynamic:false,lambda:0,energyWeight:0,capacity:600,stationsEnabled:false});moderate.run();moderate.tick(5);moderate.gust('moderate');moderate.gusts[0].endAt=Infinity;moderate.node={...moderate.position};moderate.replan('固定风况积分测试');assert.ok(moderate.feasible);let peak=0;while(moderate.status==='running'){peak=Math.max(peak,moderate.instantaneous().powerW);moderate.tick(1);}assert.equal(moderate.status,'arrived');assert.ok(peak>W.power(0,moderate.cfg)*1.4);
const target=new F.Flight();target.configure({dynamic:false,capacity:600});target.gusts=[{...W.TYPES.strong,kind:'strong',x:target.end.x,y:target.end.y,u:-18,v:0}];target.replan('目标位于危险区');assert.ok(!target.feasible);assert.ok(!target.path);
const swapping=new F.Flight();swapping.configure({dynamic:false});swapping.run();while(swapping.status==='running')swapping.tick(1);assert.equal(swapping.status,'swapping');const count=swapping.completedSwaps;swapping.gust('strong');assert.equal(swapping.decision.action,'换电后避险');assert.ok(swapping.pending);swapping.tick(swapping.swapRemaining);assert.equal(swapping.completedSwaps,count+1);assert.notEqual(swapping.decision.action,'换电后避险');
const edit=new F.Flight();edit.setPoint('start',{x:5,y:19});edit.setPoint('end',{x:54,y:22});edit.addWaypoint({x:25,y:30});edit.setWaypoint(0,{x:24,y:29});assert.deepEqual(edit.waypoints[0],{x:24,y:29});assert.throws(()=>edit.setPoint('end',edit.start));
console.log('PASS: wind/headwind/crosswind physics; moderate-gust energy increase; immediate continuous reroute; strong-core avoidance at zero risk weight; post-gust ETA/energy integration; wide-storm stop/recovery; blocked destination; swap-weather recheck; editable task points.');
